Add tests for "II architecture" part; fix testbench for simple/memory;
Testing problems:
1. http://scratch.clifford.at/coverage_html/techlibs/achronix/index.html
- in the code '-flatten' but in the help '-noflatten'
3. http://scratch.clifford.at/coverage_html/techlibs/easic/index.html -
etc/eTools is required
5. http://scratch.clifford.at/coverage_html/techlibs/gowin/index.html -
in the code '-flatten' but in the help '-noflatten'
5. http://scratch.clifford.at/coverage_html/techlibs/gowin/index.html -
for -family cyclonev: /techlibs/intel/cyclonev/cells_sim.v:88: error:
Unable to bind wire/reg/memory `upper_mask_value' in
`testbench.uut._05_.lut5'